version: '3'

services: 
    web:
        build: ./web
        ports:
            - "5000:5000"
        links: #web server or web app depends on the the database 'db'
            - db
    db:
        build: ./db